// frontend/src/prototype/mockData.js
// ISOLATED MOCK DATA FOR UX PROTOTYPE ONLY
// This file is strictly scoped to the /prototype preview and contains no real backend/production bindings.

export const MOCK_MANAGERS = [
  {
    id: "mgr-1",
    name: "Neha Kapoor",
    role: "Manager",
    department: "Sales",
    email: "neha.kapoor@netflow.mock",
    avatar: "NK",
    avatarColor: "bg-blue-600",
  },
  {
    id: "mgr-2",
    name: "Jordan Lee",
    role: "Manager",
    department: "IT",
    email: "jordan.lee@netflow.mock",
    avatar: "JL",
    avatarColor: "bg-indigo-600",
  },
  {
    id: "mgr-3",
    name: "Elena Rostova",
    role: "Manager",
    department: "Legal",
    email: "elena.rostova@netflow.mock",
    avatar: "ER",
    avatarColor: "bg-purple-600",
  },
  {
    id: "mgr-4",
    name: "Vikram Patel",
    role: "Manager",
    department: "Operations",
    email: "vikram.patel@netflow.mock",
    avatar: "VP",
    avatarColor: "bg-emerald-600",
  },
];

export const INITIAL_MOCK_REQUESTS = [
  {
    id: "req-101",
    title: "Territory Change Request",
    formType: "Territory Assignment & Quota Proposal",
    employee: "Aarav Chopra",
    employeeEmail: "aarav.chopra@netflow.mock",
    employeeAvatar: "AC",
    department: "Sales",
    submittedAt: "2026-08-18T09:30:00Z",
    submittedAgo: "2 hours ago",
    status: "Pending",
    summary: "Reallocate APAC North territory accounts following mid-year enterprise quota expansion.",
    fields: [
      { label: "Proposal ID", value: "9d63f18c-C523-4cfa-B984-50da178b594c" },
      { label: "Effective Date", value: "2026-09-01" },
      { label: "Justification", value: "Replacement for end-of-life territory distribution and Q3 expansion." },
      { label: "Attachment", value: "delivery_challan_7136.pdf", isFile: true },
      { label: "Department", value: "Sales" },
    ],
    decidedBy: null,
    decidedAt: null,
    managerComment: "",
  },
  {
    id: "req-102",
    title: "MacBook Pro M3 Hardware Upgrade",
    formType: "Hardware Procurement Request",
    employee: "Maya Lin",
    employeeEmail: "maya.lin@netflow.mock",
    employeeAvatar: "ML",
    department: "IT",
    submittedAt: "2026-08-18T08:15:00Z",
    submittedAgo: "3 hours ago",
    status: "Pending",
    summary: "Developer machine upgrade for DevOps Docker/Kubernetes local cluster testing.",
    fields: [
      { label: "Asset Tag", value: "IT-LAP-8892" },
      { label: "Device Spec", value: "Apple MacBook Pro 16\" (M3 Max, 64GB RAM, 1TB SSD)" },
      { label: "Urgency", value: "High (Current machine experiencing kernel panics)" },
      { label: "Department", value: "IT" },
    ],
    decidedBy: null,
    decidedAt: null,
    managerComment: "",
  },
  {
    id: "req-103",
    title: "Vendor Non-Disclosure Agreement (SaaS)",
    formType: "Contract Review & Signoff",
    employee: "Marcus Vance",
    employeeEmail: "marcus.vance@netflow.mock",
    employeeAvatar: "MV",
    department: "Legal",
    submittedAt: "2026-08-17T11:00:00Z",
    submittedAgo: "Yesterday at 11:00 AM",
    status: "Approved",
    summary: "Standard mutual NDA for third-party cloud data center audit vendor.",
    fields: [
      { label: "Vendor Name", value: "CloudSec Shield Ltd." },
      { label: "Governing Law", value: "State of Delaware, USA" },
      { label: "NDA Document", value: "NDA_CloudSec_v2_Signed.pdf", isFile: true },
      { label: "Department", value: "Legal" },
    ],
    decidedBy: "Elena Rostova",
    decidedAt: "2026-08-17T14:30:00Z",
    managerComment: "Terms compliant with standard NetFlow enterprise confidentiality guidelines.",
  },
  {
    id: "req-104",
    title: "Software License Procurement (Figma Ent)",
    formType: "Software & SaaS Purchase",
    employee: "Priya Sharma",
    employeeEmail: "priya.sharma@netflow.mock",
    employeeAvatar: "PS",
    department: "IT",
    submittedAt: "2026-08-16T15:20:00Z",
    submittedAgo: "2 days ago",
    status: "Rejected",
    summary: "5 dedicated enterprise seats for internal workflow UI prototyping.",
    fields: [
      { label: "Software", value: "Figma Enterprise Plan (5 seats)" },
      { label: "Total Cost", value: "$4,500 / year" },
      { label: "Cost Center", value: "IT-DEV-2026" },
      { label: "Department", value: "IT" },
    ],
    decidedBy: "Jordan Lee",
    decidedAt: "2026-08-16T18:10:00Z",
    managerComment: "Budget limit exceeded for Q3 SaaS tooling. Please bundle this request with the annual IT department pool during October budgeting.",
  },
  {
    id: "req-105",
    title: "Q4 Travel & Client Workshop Advance",
    formType: "Travel & Expense Pre-Approval",
    employee: "David Kim",
    employeeEmail: "david.kim@netflow.mock",
    employeeAvatar: "DK",
    department: "Sales",
    submittedAt: "2026-08-15T14:00:00Z",
    submittedAgo: "3 days ago",
    status: "Rejected",
    summary: "On-site customer onboarding travel to Chicago headquarters for 3 days.",
    fields: [
      { label: "Destination", value: "Chicago, IL, USA" },
      { label: "Estimated Cost", value: "$1,850.00" },
      { label: "Dates", value: "2026-09-12 to 2026-09-15" },
      { label: "Department", value: "Sales" },
    ],
    decidedBy: "Neha Kapoor",
    decidedAt: "2026-08-15T16:45:00Z",
    managerComment: "Missing client invitation letter and flight cost comparison sheet. Please attach both items and resubmit.",
  },
];

export const MOCK_EMPLOYEES_ROSTER = [
  // IT Department Employees
  {
    id: "emp-it-1",
    name: "Alex Rivera",
    role: "Senior Cloud Engineer",
    department: "IT",
    email: "alex.rivera@netflow.mock",
    status: "Active",
    openTasks: 3,
    slaCompliance: "98%",
    lastActive: "10 mins ago",
    avatar: "AR",
    avatarColor: "bg-indigo-500",
  },
  {
    id: "emp-it-2",
    name: "Maya Lin",
    role: "DevOps Specialist",
    department: "IT",
    email: "maya.lin@netflow.mock",
    status: "Active",
    openTasks: 5,
    slaCompliance: "95%",
    lastActive: "Just now",
    avatar: "ML",
    avatarColor: "bg-teal-500",
  },
  {
    id: "emp-it-3",
    name: "Priya Sharma",
    role: "Security & Systems Analyst",
    department: "IT",
    email: "priya.sharma@netflow.mock",
    status: "Active",
    openTasks: 2,
    slaCompliance: "100%",
    lastActive: "1 hour ago",
    avatar: "PS",
    avatarColor: "bg-purple-500",
  },
  {
    id: "emp-it-4",
    name: "Lucas Gray",
    role: "IT Support Lead",
    department: "IT",
    email: "lucas.gray@netflow.mock",
    status: "Active",
    openTasks: 1,
    slaCompliance: "92%",
    lastActive: "35 mins ago",
    avatar: "LG",
    avatarColor: "bg-sky-500",
  },

  // Sales Department Employees
  {
    id: "emp-sales-1",
    name: "Aarav Chopra",
    role: "Enterprise Account Executive",
    department: "Sales",
    email: "aarav.chopra@netflow.mock",
    status: "Active",
    openTasks: 4,
    slaCompliance: "96%",
    lastActive: "Just now",
    avatar: "AC",
    avatarColor: "bg-blue-500",
  },
  {
    id: "emp-sales-2",
    name: "David Kim",
    role: "Regional Sales Lead",
    department: "Sales",
    email: "david.kim@netflow.mock",
    status: "Active",
    openTasks: 6,
    slaCompliance: "89%",
    lastActive: "15 mins ago",
    avatar: "DK",
    avatarColor: "bg-amber-500",
  },
  {
    id: "emp-sales-3",
    name: "Chloe Bennet",
    role: "Sales Development Rep",
    department: "Sales",
    email: "chloe.bennet@netflow.mock",
    status: "Active",
    openTasks: 2,
    slaCompliance: "97%",
    lastActive: "40 mins ago",
    avatar: "CB",
    avatarColor: "bg-pink-500",
  },
  {
    id: "emp-sales-4",
    name: "Ryan Chen",
    role: "Pre-Sales Solutions Architect",
    department: "Sales",
    email: "ryan.chen@netflow.mock",
    status: "Active",
    openTasks: 3,
    slaCompliance: "94%",
    lastActive: "2 hours ago",
    avatar: "RC",
    avatarColor: "bg-emerald-500",
  },

  // Legal Department Employees
  {
    id: "emp-legal-1",
    name: "Marcus Vance",
    role: "Senior Corporate Counsel",
    department: "Legal",
    email: "marcus.vance@netflow.mock",
    status: "Active",
    openTasks: 2,
    slaCompliance: "100%",
    lastActive: "20 mins ago",
    avatar: "MV",
    avatarColor: "bg-purple-600",
  },
  {
    id: "emp-legal-2",
    name: "Sophia Alva",
    role: "Compliance & Regulatory Specialist",
    department: "Legal",
    email: "sophia.alva@netflow.mock",
    status: "Active",
    openTasks: 4,
    slaCompliance: "97%",
    lastActive: "50 mins ago",
    avatar: "SA",
    avatarColor: "bg-rose-500",
  },
  {
    id: "emp-legal-3",
    name: "Rachel Zane",
    role: "Contract Paralegal",
    department: "Legal",
    email: "rachel.zane@netflow.mock",
    status: "Active",
    openTasks: 1,
    slaCompliance: "99%",
    lastActive: "3 hours ago",
    avatar: "RZ",
    avatarColor: "bg-indigo-600",
  },

  // Operations Department Employees
  {
    id: "emp-ops-1",
    name: "Tara Singh",
    role: "Logistics Operations Lead",
    department: "Operations",
    email: "tara.singh@netflow.mock",
    status: "Active",
    openTasks: 5,
    slaCompliance: "93%",
    lastActive: "5 mins ago",
    avatar: "TS",
    avatarColor: "bg-emerald-600",
  },
  {
    id: "emp-ops-2",
    name: "Carlos Gomez",
    role: "Supply Chain & Procurement Analyst",
    department: "Operations",
    email: "carlos.gomez@netflow.mock",
    status: "Active",
    openTasks: 3,
    slaCompliance: "91%",
    lastActive: "1 hour ago",
    avatar: "CG",
    avatarColor: "bg-orange-500",
  },
  {
    id: "emp-ops-3",
    name: "Nina Patel",
    role: "Facilities & Workplace Manager",
    department: "Operations",
    email: "nina.patel@netflow.mock",
    status: "Active",
    openTasks: 2,
    slaCompliance: "98%",
    lastActive: "4 hours ago",
    avatar: "NP",
    avatarColor: "bg-violet-500",
  },
];
